(function () {
const games=Array.isArray(window.GAMES)?window.GAMES:[];
const grid=document.getElementById("grid"),count=document.getElementById("count"),search=document.getElementById("search");
const genre=document.getElementById("genre-filter"),year=document.getElementById("year-filter"),sort=document.getElementById("sort-filter");
const editions=document.querySelectorAll("#editions button");
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function fill(){let gs=[...new Set(games.map(g=>String(g.genero||"").trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"pt-BR")),ys=[...new Set(games.map(g=>String(g.year||"").trim()).filter(Boolean))].sort((a,b)=>Number(b)-Number(a));genre.innerHTML='<option value="">GÊNERO</option>'+gs.map(x=>'<option>'+esc(x)+'</option>').join("");year.innerHTML='<option value="">ANO</option>'+ys.map(x=>'<option>'+esc(x)+'</option>').join("")}
function render(list){let groups={};list.forEach(g=>(groups[g.year||"Sem ano"]??=[]).push(g));let years=Object.keys(groups).sort((a,b)=>sort.value!=="default"?0:(Number(b)||0)-(Number(a)||0));grid.innerHTML=years.map(y=>{let js=groups[y],m=Math.max(1,Math.min(10,Math.floor((innerWidth+34)/174))),n=Math.ceil(js.length/m),base=Math.floor(js.length/n),rem=js.length%n,rows=[],i=0;for(let r=0;r<n;r++){let z=base+(r<rem?1:0);rows.push(js.slice(i,i+z));i+=z}return '<section class="year-section"><div class="year-title">'+esc(y)+'</div><div class="year-grid">'+rows.map(row=>'<div class="game-row">'+row.map(g=>'<a class="card" href="jogo.html?id='+encodeURIComponent(g.id)+'"><img class="thumb" src="'+esc(g.thumb||g.image)+'" alt="'+esc(g.name)+'" loading="lazy"><div class="name">'+esc(g.name)+'</div></a>').join("")+'</div>').join("")+'</div></section>'}).join("");count.textContent=list.length+" jogos"}
function apply(){let q=search.value.trim().toLowerCase(),gs=editions.length?[...editions].filter(b=>b.classList.contains("active")).map(b=>b.dataset.edition):[];let list=games.filter(g=>(!q||String(g.name).toLowerCase().includes(q))&&(!genre.value||String(g.genero||"").trim()===genre.value)&&(!year.value||String(g.year||"").trim()===year.value)&&(!gs.length||gs.includes(String(g.edition||"").toUpperCase())));if(sort.value==="az")list.sort((a,b)=>a.name.localeCompare(b.name,"pt-BR"));if(sort.value==="za")list.sort((a,b)=>b.name.localeCompare(a.name,"pt-BR"));render(list)}
[search,genre,year,sort].forEach(x=>x.addEventListener(x===search?"input":"change",apply));editions.forEach(b=>b.addEventListener("click",()=>{b.classList.toggle("active");apply()}));fill();apply();addEventListener("resize",apply);
})();